name: Downstream CI

on:
  repository_dispatch:
    types: [trigger-b-ci]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI
        run: |
          echo "Running B CI..."
          sleep 10
          echo "Done"

      - name: Report result to server
        if: always()
        env:
          SERVER_URL: http://111.119.217.84:8000
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            RESULT=success
          else
            RESULT=failure
          fi

          curl -X POST $SERVER_URL/ci/result \
            -H "Content-Type: application/json" \
            -d "{
              \"a_repo\": \"${{ github.event.client_payload.a_repo }}\",
              \"a_sha\": \"${{ github.event.client_payload.a_sha }}\",
              \"conclusion\": \"$RESULT\",
              \"url\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
            }"
